# unogroup-app/k8s/overlays/prod/serviceaccount-patch.yaml
# TODO: reemplazar por el GSA real con permiso IAM sobre los secretos de
# Solution One en GCP Secret Manager (Diseño §2.3/§2.4).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unogroup-app-sa
  annotations:
    iam.gke.io/gcp-service-account: unogroup-app@TBD_PROJECT_ID.iam.gserviceaccount.com
